"""fix token lenght

Revision ID: 5cf462d8b3a5
Revises: ce53ce659f8d
Create Date: 2025-12-13 21:05:50.372480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf462d8b3a5'
down_revision: Union[str, None] = 'ce53ce659f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE auth.login_history ALTER COLUMN token TYPE TEXT;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
